FROM golang:1.26-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0

RUN go build -o smtp-webhook-server .

EXPOSE 2525

ENTRYPOINT ["/app/smtp-webhook-server"]

CMD [
"--listen=:2525",
"--timeout.read=60",
"--timeout.write=60"
]
